// Runs before `docusaurus start`/`build` (see package.json "pre*" scripts).
//
// Reads every page under content/docs/, checks its `visibility` frontmatter
// (public | internal), and copies only the allowed subset into docs/ — the
// folder Docusaurus actually reads content from. Two sites built from the
// same repo with different SITE_AUDIENCE values end up with different docs/
// folders, and therefore different sidebars, from one tagged source.
//
// Also writes (or removes) a Netlify _headers file so the "internal" build
// requires a login on the whole site, while "public" stays open.

import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");

const SOURCE_DIR = path.join(root, "content", "docs");
const OUTPUT_DIR = path.join(root, "docs");
const STATIC_DIR = path.join(root, "static");
const HEADERS_PATH = path.join(STATIC_DIR, "_headers");

// Default to "internal" (the superset) so local dev and any deployment that
// doesn't explicitly set SITE_AUDIENCE shows everything. Set to "public" as a
// build environment variable on the public Netlify site to filter it down.
const audience = (process.env.SITE_AUDIENCE || "internal").trim().toLowerCase();

if (audience !== "public" && audience !== "internal") {
  console.error(
    `[prepare-build] Invalid SITE_AUDIENCE "${audience}" — expected "public" or "internal". Defaulting to "internal".`
  );
}
const effectiveAudience = audience === "public" ? "public" : "internal";

console.log(`[prepare-build] SITE_AUDIENCE=${effectiveAudience}`);

function isAllowed(visibility) {
  // Missing/unrecognized visibility defaults to public — safer default than
  // accidentally leaking a page by requiring an explicit "internal" tag.
  const v = (visibility || "public").trim().toLowerCase();
  if (effectiveAudience === "internal") return true;
  return v === "public";
}

function copyFiltered(srcDir, destDir) {
  const entries = fs.readdirSync(srcDir, { withFileTypes: true });

  for (const entry of entries) {
    const srcPath = path.join(srcDir, entry.name);

    if (entry.isDirectory()) {
      const destPath = path.join(destDir, entry.name);
      fs.mkdirSync(destPath, { recursive: true });
      copyFiltered(srcPath, destPath);
      // Prune the directory if nothing survived the filter inside it.
      if (fs.readdirSync(destPath).length === 0) {
        fs.rmdirSync(destPath);
      }
      continue;
    }

    if (entry.name.endsWith(".md") || entry.name.endsWith(".mdx")) {
      const raw = fs.readFileSync(srcPath, "utf8");
      const { data } = matter(raw);
      if (!isAllowed(data.visibility)) continue;
      fs.mkdirSync(destDir, { recursive: true });
      fs.copyFileSync(srcPath, path.join(destDir, entry.name));
    } else {
      // Non-markdown assets (images, etc.) always come along untouched.
      fs.mkdirSync(destDir, { recursive: true });
      fs.copyFileSync(srcPath, path.join(destDir, entry.name));
    }
  }
}

// Rebuild docs/ from scratch each time so stale filtered-out pages never linger.
fs.rmSync(OUTPUT_DIR, { recursive: true, force: true });
fs.mkdirSync(OUTPUT_DIR, { recursive: true });
copyFiltered(SOURCE_DIR, OUTPUT_DIR);

const countMd = (dir) => {
  let n = 0;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) n += countMd(path.join(dir, entry.name));
    else if (entry.name.endsWith(".md") || entry.name.endsWith(".mdx")) n += 1;
  }
  return n;
};
console.log(`[prepare-build] Copied ${countMd(OUTPUT_DIR)} page(s) into docs/`);

// Netlify-only whole-site Basic Auth for the internal build. Harmless on
// GitHub Pages/Cloudflare (they either ignore this file or don't read it as
// an auth directive) — see SETUP_PERSONAL_ACCOUNT.md for the caveats.
fs.mkdirSync(STATIC_DIR, { recursive: true });
if (effectiveAudience === "internal") {
  const headers = [
    "# Generated by scripts/prepare-build.mjs — DEMO CREDENTIALS ONLY.",
    "# Change these, and note that because this repo is public, anyone can",
    "# read this password directly from the source.",
    "/*",
    "  Basic-Auth: demo:letmein",
    "",
  ].join("\n");
  fs.writeFileSync(HEADERS_PATH, headers);
  console.log("[prepare-build] Wrote static/_headers (whole-site Basic Auth for internal build)");
} else if (fs.existsSync(HEADERS_PATH)) {
  fs.rmSync(HEADERS_PATH);
  console.log("[prepare-build] Removed static/_headers (public build stays open)");
}
